Heroes/HeroesUnleashed/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("create/", include("create.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Heroes/create/urls.py
from django.urls import path

from . import views

app_name = "create"

urlpatterns = [
    path("", views.index, name="index"),
    path("heroes/", views.heroes, name="heroes"),
    path("hero/<int:hero_id>", views.hero, name="hero"),
    path("deleted/<int:hero_id>/", views.deleted, name="deleted"),
    path("party/", views.party, name="party"),
]

Heroes/create/models.py
from typing import Any
from django.db import models

from time import time, mktime
from datetime import datetime


class Avatar(models.Model):
    avatar = models.ImageField(upload_to="avatars")
    name = models.CharField(max_length=32)

    def __str__(self):
        return f"{self.name}"


class Party(models.Model):
    name = models.CharField(max_length=32, default="Party")

    def __str__(self):
        return f"{self.name}"


class Hero(models.Model):
    name = models.CharField(max_length=32)
    created = models.DateTimeField(default=datetime.now())
    avatar = models.ForeignKey(Avatar, on_delete=models.CASCADE, blank=True, null=True)
    party = models.ForeignKey(Party, on_delete=models.SET_NULL, blank=True, null=True)
    party_member = models.BooleanField(default=False)

    def exp(self):
        """Returns experience gained so far since time created."""
        return int(time() - mktime(self.created.timetuple()))

    def level(self):
        """Level 1 - 10k,Level 7 - 70k, each level needs 10k more exp than the previous."""
        level = 1
        base = 10000

        while Hero.exp(self) > base:
            level += 1
            base += 10000 * level

        return level

    def exp_percentage(self):
        """Returns the percentage needed for the experience bar."""
        max_exp_this_level = Hero.level(self) * 10000

        # Divides exp to level up with max xp for this level.
        exp_coeff = Hero.exp_to_level_up(self) / max_exp_this_level

        # Creates a 0 < number < 100 from the exp coefficient.
        percentage = (1 - exp_coeff) * 100

        # Rounds the number with 2 digits after the decimal.
        return round(percentage, 2)

    def exp_to_level_up(self):
        """Returns the experience needed for level up."""
        total_exp = 0

        # Calculates the total exp for this level.
        for i in range(Hero.level(self) + 1):
            total_exp += 10000 * i

        # Difference between total and current exp.
        return total_exp - Hero.exp(self)

    def level_up_date(self):
        """Returns the date on which the level up will occur."""

        # for this level or the time range from creation up until the moment of leveling up.
        total_exp = Hero.exp(self) + Hero.exp_to_level_up(self)

        # Adds the time range till creation with the one from creation till level up.
        x = int((mktime(self.created.timetuple())) + total_exp)

        # Converts the sum to a date.
        return datetime.fromtimestamp(x)

    def __str__(self):
        return f"{self.name}"

Heroes/create/views.py
from django.shortcuts import render, get_object_or_404

from django import forms

from .models import *


class HeroForm(forms.Form):
    name = forms.CharField(
        label="name", widget=forms.TextInput(attrs={"placeholder": "Choose a new name"})
    )


class PartyForm(forms.Form):
    hero_selection = forms.ModelMultipleChoiceField(
        queryset=Hero.objects.filter(party_member=False)
    )


def index(request):
    return render(request, "create/index.html")


def heroes(request):
    form = HeroForm()

    if request.method == "POST":
        if request.POST["name"]:
            new_hero = Hero(name=request.POST["name"])

        new_hero.save()

    heroes = Hero.objects.all()

    return render(request, "create/heroes.html", {"heroes": heroes, "form": form})


def hero(request, hero_id):
    form = HeroForm()
    avatars = Avatar.objects.all()
    hero = get_object_or_404(Hero, pk=hero_id)

    if request.method == "POST":
        if "new_avatar" in request.POST:
            hero.avatar = Avatar.objects.get(id=request.POST["new_avatar"])

        if "name" in request.POST:
            hero.name = request.POST["name"]

        if "detele" in request.POST:
            pass

    hero.save()
    hero = get_object_or_404(Hero.objects.filter(pk=hero_id))

    return render(
        request,
        "create/hero.html",
        {"hero": hero, "form": form, "avatars": avatars},
    )


def deleted(request, hero_id):
    hero = get_object_or_404(Hero, pk=hero_id)
    name = hero.name
    hero.delete()

    return render(request, "create/deleted.html", {"name": name})


def party(request):
    form = PartyForm()

    if request.method == "POST":
        if "hero_selection" in request.POST:
            party = (
                Party.objects.last()
                if Party.objects.exists()
                else Party.objects.create()
            )

            for id in request.POST.getlist("hero_selection"):
                hero = get_object_or_404(Hero, pk=id)

                party = (
                    Party.objects.last()
                    if party.hero_set.all().count() < 4
                    else Party.objects.create()
                )

                hero.party = party
                hero.party_member = True
                hero.save()

        if "delete" in request.POST:
            if Party.objects.exists():
                party = get_object_or_404(Party, pk=request.POST["delete"])

                for hero in party.hero_set.all():
                    hero.party_member = False
                    hero.save()

                party.delete()

    parties = Party.objects.all() if Party.objects.exists() else []

    return render(
        request,
        "create/party.html",
        {"form": form, "parties": parties},
    )

Heroes/create/templates/create/deleted.html
{% extends 'create/layout.html' %} {% block body %}
<h1>Successfully deleted {{ name }}</h1>
<h1>
    <a href="{% url 'create:index' %}">Go to Heroes section.</a>
</h1>

{% endblock %}

Heroes/create/templates/create/hero.html
{% extends 'create/layout.html' %} {% block body %} {% load static %}
<script src="{% static 'create/exp_bar.js' %}?{% now 'U' %}" defer></script>
<h1>{{ hero.name }}</h1>
<div class="div_hero">
    <img src="{{ hero.avatar.avatar.url }}" alt="loading" />
    <div class="div_hero__details">
        <h4>Level - {{ hero.level }}</h4>
        <div class="div_exp_bar">
            <input type="hidden" id="exp_percentage" name="exp" value="{{ hero.exp_percentage }}" />
            <div id="exp_bar">{{ hero.exp_percentage }}</div>
        </div>
        <h4>Experience gained - {{ hero.exp }}</h4>
        <h4>Next level will be on the {{ hero.level_up_date }}</h4>

        <h5>Adventure Began - {{ hero.created }}</h5>
    </div>
    <div class="div_hero__forms">
        <form class="div_hero__forms_update" action="{% url 'create:hero' hero.id %}" method="post">
            {% csrf_token %} {{ form }}
            <input class="button" type="submit" value="Update" />
        </form>
        <form class="div_hero__forms_delete" action="{% url 'create:deleted' hero.id %}" method="post">
            {% csrf_token %}
            <input class="button" type="submit" value="Delete" />
        </form>
    </div>
</div>

<div class="div_hero__avatars">
    <h1>Avatar.</h1>
    <form class="div_hero__avatars_form" action="{% url 'create:hero' hero.id %}" method="post">
        <div class="div_hero__avatar">
            {% csrf_token %} {% for avatar in avatars %}
            <div class="div_hero__avatar_details">
                <label for="{{ avatar.id }}"><img src="{{ avatar.avatar.url }}" alt="loading" />
                </label>
                <input type="radio" id="{{ avatar.id }}" name="new_avatar" value="{{ avatar.id }}" />
            </div>

            {% empty %}
            <h1>No avatars.</h1>
            {% endfor %}
        </div>

        <input type="submit" value="Change Avatar" />
    </form>
</div>

<h1>
    <a href="{% url 'create:heroes' %}">Go to Heroes section.</a>
</h1>
{% endblock %}

Heroes/create/templates/create/heroes.html
{% extends 'create/layout.html' %} {% block body %}
<div class="div_index">
    <form class="div_index__form" action="{% url 'create:heroes' %}" method="post">
        {% csrf_token %} {{ form }}
        <input class="button" type="submit" value="Create Hero" />
    </form>
    <div class="div_index__heroes">
        {% for hero in heroes %}
        <div class="div_index__hero">
            <a class="hero_name" href="{% url 'create:hero' hero.id %}">{{ hero.name }}</a>
            <img src="{{ hero.avatar.avatar.url }}" alt="loading" />
        </div>

        {% empty %}
        <h1>No Heroes</h1>
        {% endfor %}
    </div>
</div>

{% endblock %}

Heroes/create/templates/create/index.html
{% extends 'create/layout.html' %} {% block body %}
<h1>index</h1>
{% endblock %}

Heroes/create/templates/create/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'create/styles.css' %}?{% now 'U' %}" />
    <title>Create</title>
</head>

<body>
    <nav>
        <ul class="main-nav">
            <li><a href="{% url 'create:heroes' %}">Heroes</a></li>
            <li><a href="{% url 'create:party' %}">Parties</a></li>
            <li class="push">
                <a href="{% url 'create:index' %}">Home</a>
            </li>
        </ul>
    </nav>
    {% block body %} {% endblock %}
</body>

</html>

Heroes/create/templates/create/party.html
{% extends 'create/layout.html' %} {% block body %}
<div class="div_party">
    <form class="party__form" action="{% url 'create:party' %}" method="post">
        {% csrf_token %} {{ form }}
        <input class="button" type="submit" value="Join Party" />
    </form>
    <div class="div_party__parties">
        <div class="div_party__party">
            {% for party in parties %}
            <div class="div_party__navigation">
                <h4 id="party_name">{{ party.name }}{{ party.id }}</h4>
                <form action="{% url 'create:party' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="delete" value="{{ party.id }}" />
                    <input class="button" type="submit" value="Delete Party" />
                </form>
            </div>
            <div class="div_party__heroes">
                {% for hero in party.hero_set.all %}
                <div class="div_party__hero">
                    <p class="hero_name">{{ hero.name }}</p>
                    <img src="{{ hero.avatar.avatar.url }}" alt="loading" />
                </div>
                {% empty %}
                <h3>Empty Party</h3>
                {% endfor %}
            </div>
            {% empty %}
            <h1>Add a party</h1>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}